postgresql:
  username: cart
  password: cart
  schema: cart
  url: localhost:3306

redis-connection:
  host: localhost
  port: "6379"

server:
  port: ${PORT:8080}
  undertow:
    threads:
      worker: 10
      io: 2